### PR TITLE
Update to version v0.4 for compatibility with axum v0.6

### PR DESCRIPTION
**Pull request by Congyuwang**
update axum-core to v0.3 to support axum v0.6.

### CODE REVIEW

**Comment by Owez** [comment]
Thanks for this PR, sorry for not doing it myself. Checking now

**Review by Owez — APPROVED** [review]
Looks good

**Comment by Owez** [comment]
Ill test and merge after the England match :)

**Comment by BerkeinR** [comment]
Since Belgium has been eliminated, I have some spare time for coding but I stumbled on this bug so did you find any free time already for testing and merging it?

**Comment by Owez** [comment]
> Since Belgium has been eliminated, I have some spare time for coding but I stumbled on this bug so did you find any free time already for testing and merging it?

I cloned and tested it but forgot to press the merge button

**Comment by BerkeinR** [comment]
> > Since Belgium has been eliminated, I have some spare time for coding but I stumbled on this bug so did you find any free time already for testing and merging it?
> 
> I cloned and tested it but forgot to press the merge button

Oh np, thx for merging it :)

**Comment by Owez** [comment]
I've finally got some time to do some dev so some more features are coming soon, is there anything you'd like for auth on this crate?

**Comment by BerkeinR** [comment]
> I've finally got some time to do some dev so some more features are coming soon, is there anything you'd like for auth on this crate?

Thx for asking but I've only been developing in rust for a few months now so I'm still exploring crates and getting used to some implementations. But from what I understand you've implemented some custom extractors for basic and bearer authentication. Is the scope the project limited to extractors or could OAuth2 be something we could see in the future?

**Comment by Owez** [comment]
> > I've finally got some time to do some dev so some more features are coming soon, is there anything you'd like for auth on this crate?
> 
> Thx for asking but I've only been developing in rust for a few months now so I'm still exploring crates and getting used to some implementations. But from what I understand you've implemented some custom extractors for basic and bearer authentication. Is the scope the project limited to extractors or could OAuth2 be something we could see in the future?

I've thought about this a bit and I'm not sure to be honest. OAuth is a bit tricky but it _can_ be done, I think something more centralised like Auth0 or others could work well, but at the same time there are already crates for them. Right now I'm creating a passwordless auth platform which would allow you to easily add entire login boxes to axum as a guard, but obviously I dont want to destroy this oss general crate by being greedy and implementing that – I think locked-in services should stay out of this project.

I think I'll stick to making nice http basic/bearer auth stuff for now in this crate, and then maybe try to implement some platform agnostic OAuth bindings eventually so you can implement stuff like google/facebok logins using their tokens. Thanks for the feedback :)

**Pull request merged**
