### PR TITLE
Split crate into features

### PR DESCRIPTION
**Pull request by HigherOrderLogic**
Split crate into features to reduce compile time

### CODE REVIEW

**Review by Owez — APPROVED** [review]
Seems good, thanks for the PR :)

**Comment by Owez** [comment]
I'll push the crate tomorrow, deciding if this should be a breaking change or not. I think it could be a patch but the dep change could break somehow somewhere.

**Comment by HigherOrderLogic** [comment]
> I'll push the crate tomorrow, deciding if this should be a breaking change or not. I think it could be a patch but the dep change could break somehow somewhere.

This shouldn't be a breaking change since all components are included in the default feature, and `axum` originally includes `axum-core` so old code would work without any problem.

**Comment by Owez** [comment]
I agree, but I published as `0.3` after talking to someone on the community server. They pointed out `default-features = false` could've been in somebodies deps even though nobody should be doing that. It's non-breaking for the code but technically breaking for somebodies misconfigured toml file :)

**Pull request merged**
